apiVersion: v1
kind: Service

metadata:
  name: demo-api-service

spec:
  type: NodePort

  selector:
    app: demo-api
    version: blue

  ports:

  - port: 3000
    targetPort: 3000
    nodePort: 30090
