on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    uses: valentina-ochoa/MiProyecto-SharedWorkflows/.github/workflows/deploy-api.yaml@pipeTest

    with:
      image-name: mi-api
      image-tag: ${{ github.ref_name }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
